callbacks: fix compiler error with older rust versions
current MSRV is 1.41, and without this fix the following errors occur after
the previous callback enhancement, for versions up to and including 1.45.
it does not occur with 1.46 onwards.

(as caught by CI: https://github.com/jnqnfe/pulse-binding-rust/runs/1658038965?check_suite_focus=true)

error[E0596]: cannot borrow data in a dereference of `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>` as mutable
   --> pulse-binding/src/callbacks.rs:167:13
    |
167 |             (callback)(ListResult::Item(&item));
    |             ^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>`

error[E0596]: cannot borrow data in a dereference of `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>` as mutable
   --> pulse-binding/src/callbacks.rs:173:13
    |
173 |             (callback)(ListResult::End);
    |             ^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>`

error[E0596]: cannot borrow data in a dereference of `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>` as mutable
   --> pulse-binding/src/callbacks.rs:177:13
    |
177 |             (callback)(ListResult::Error);
    |             ^^^^^^^^^^ cannot borrow as mutable
    |
    = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::mem::ManuallyDrop<std::boxed::Box<std::boxed::Box<dyn for<'r> std::ops::FnMut(callbacks::ListResult<&'r Item>)>>>`