Revert "context: convert method from `dyn Mainloop` to `impl Mainloop`"
This change introduced an E0632 error in my test app:

error[E0632]: cannot provide explicit type parameters when `impl Trait` is used in argument position.
   --> src/main.rs:213:41
    |
213 |     let _t_event = context.borrow_mut().rttime_new::<Mainloop, _>(&*mainloop.borrow(),
    |

Removing `::<Mainloop, _>` gave an error insisting that type annotation was
required on the variable capturing the result, but I could not figure out a
working type annotation.

This reverts commit f9e64a72be053b6df633612b13ec85c8755d0864.